// Code generated by goctl. DO NOT EDIT.
package types

type ArticleInfo struct {
	Id uint `json:"id"`
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type BlogCategoryInfo struct {
	Id    uint   `json:"id"`
	Cover string `json:"cover"`
	Name  string `json:"name"`
	Des   string `json:"des"`
}

type BlogComments struct {
	Id            uint                 `json:"id"`
	Created       int                  `json:"created"`
	Content       string               `json:"content"`
	ArticleId     uint                 `json:"article_id"`
	CommentId     uint                 `json:"comment_id"`
	WebsiteUserId uint                 `json:"website_user_id"`
	UserId        uint                 `json:"user_id"`
	Type          string               `json:"type"`
	User          BlogCommentsUserInfo `json:"user"`
}

type BlogCommentsUserInfo struct {
	Id       uint   `json:"id"`
	Uid      string `json:"uid"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type BlogSearchByIdReq struct {
	Id uint `form:"id"`
}

type BlogSearchByIdRes struct {
	Base
	Data BlogSearchByIdResData `json:"data"`
}

type BlogSearchByIdResData struct {
	Info ListBlogItem `json:"info"`
}

type BlogSearchByIdsListInfo struct {
	Id    uint   `json:"id"`
	Uid   string `json:"uid"`
	Title string `json:"title"`
	Des   string `json:"des"`
	Cover string `json:"cover"`
}

type BlogSearchByIdsReq struct {
	Ids []uint `json:"ids"`
}

type BlogSearchByIdsRes struct {
	Base
	Data BlogSearchByIdsResData `json:"data"`
}

type BlogSearchByIdsResData struct {
	Info []BlogSearchByIdsListInfo `json:"info"`
}

type BlogSearchByUserIdInfo struct {
	Id      uint   `json:"id"`
	Title   string `json:"title"`
	Des     string `json:"des"`
	Cover   string `json:"cover"`
	Created int64  `json:"created"`
	Updated int64  `json:"updated"`
}

type BlogSearchByUserIdReq struct {
	Page  int  `json:"page"`
	Limit int  `json:"limit"`
	Id    uint `json:"id"`
}

type BlogSearchByUserIdRes struct {
	Base
	Data BlogSearchByUserIdResData `json:"data"`
}

type BlogSearchByUserIdResData struct {
	Count int64                    `json:"count"`
	Infos []BlogSearchByUserIdInfo `json:"infos"`
}

type BlogTags struct {
	Id      uint   `json:"id" json:"id"`
	Uid     string `json:"uid"`
	TagName string `json:"tag_name""`
	Type    string `json:"type"`
}

type BlogUserInfo struct {
	Id       uint   `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Motto    string `json:"motto"`
}

type CategorieInfo struct {
	Id    uint   `json:"id"`
	Cover string `json:"cover"`
	Name  string `json:"name"`
	Des   string `json:"des"`
}

type CategoryIdSearchReq struct {
	Id     uint `form:"id"`
	UserId uint `form:"user_id"`
}

type CategoryIdSearchRes struct {
	Base
	Data CategoryIdSearchResData `json:"data"`
}

type CategoryIdSearchResData struct {
	Infos []SearchResDataInfo `json:"infos"`
}

type CommentCreateReq struct {
	Content       string `json:"content"`
	ArticleId     uint   `json:"article_id,optional"`
	CommentId     uint   `json:"comment_id,optional"`
	WebsiteUserId uint   `json:"website_user_id,optional"`
	Type          string `json:"type,options=[article,comment,website]"`
}

type CommentCreateRes struct {
	Base
}

type CommentDeleteReq struct {
	Id uint `json:"id"`
}

type CommentDeleteRes struct {
	Base
}

type CommentInfo struct {
	Id            uint            `json:"id"`
	Created       int             `json:"created"`
	Content       string          `json:"content"`
	ArticleId     uint            `json:"article_id"`
	CommentId     uint            `json:"comment_id"`
	WebsiteUserId uint            `json:"website_user_id"`
	UserId        uint            `json:"user_id"`
	Type          string          `json:"type"`
	User          CommentUserInfo `json:"user"`
}

type CommentListReq struct {
	Id   uint   `form:"id"`
	Type string `form:"type,options=[article,comment,website]"`
}

type CommentListRes struct {
	Base
	Data CommentListResData `json:"data"`
}

type CommentListResData struct {
	Count int64         `json:"count"`
	Info  []CommentInfo `json:"info"`
}

type CommentUserInfo struct {
	Id       uint   `json:"id"`
	Uid      string `json:"uid"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type CreateBlogReq struct {
	Title      string `json:"title"`
	Des        string `json:"des"`
	Cover      string `json:"cover"`
	Content    string `json:"content"`
	Tags       []uint `json:"tags,optional"`
	Keywords   string `json:"keywords"`
	CategoryId uint   `json:"category_id,optional"`
}

type CreateBlogRes struct {
	Base
	Data CreateBlogResData `json:"data"`
}

type CreateBlogResData struct {
	Id uint `json:"id"`
}

type CreateCategorieReq struct {
	Cover string `json:"cover"`
	Name  string `json:"name"`
	Des   string `json:"des"`
}

type CreateCategorieRes struct {
	Base
}

type CreateTagReq struct {
	Name string `json:"name"`
	Type string `json:"type,options=[article,image]"`
}

type CreateTagRes struct {
	Base
}

type DeleteBlogReq struct {
	Id uint `json:"id"`
}

type DeleteBlogRes struct {
	Base
}

type DeleteCategorieReq struct {
	Id uint `json:"id"`
}

type DeleteTagReq struct {
	Id uint `json:"id"`
}

type DeleteTagRes struct {
	Base
}

type DetleteCategorieRes struct {
	Base
}

type EmailSendCodeReq struct {
	Email string `json:"email"`
}

type EmailSendCodeRes struct {
	Base
}

type FileDeleteReq struct {
	Id       uint   `json:"id"`
	FilePath string `json:"file_path"`
	Type     string `json:"type,options=[blog,images,avatar,bg,categories]"`
}

type FileDeleteRes struct {
	Base
}

type FileInfo struct {
	Id       uint   `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
	Status   bool   `json:"status"`
	W        int    `json:"w"`
	H        int    `json:"h"`
}

type FileListPublicReq struct {
	Id    uint `form:"id"`
	Page  int  `form:"page"`
	Limit int  `form:"limit"`
}

type FileListPublicRes struct {
	Base
	Data FileListPublicResData `json:"data"`
}

type FileListPublicResData struct {
	Count int64                       `json:"count"`
	Infos []FileListPublicResDataInfo `json:"infos"`
}

type FileListPublicResDataInfo struct {
	Id       uint   `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
	Status   bool   `json:"status"`
	W        int    `json:"w"`
	H        int    `json:"h"`
}

type FileListReq struct {
	Page  int    `form:"page,optional"`
	Limit int    `form:"limit,optional"`
	Type  string `form:"type,options=[blog,images,avatar,bg,categories]"`
}

type FileListRes struct {
	Base
	Data FileListResdata `json:"data"`
}

type FileListResdata struct {
	Count int64      `json:"count"`
	Infos []FileInfo `json:"infos"`
}

type FileStatusReq struct {
	Id     uint `json:"id"`
	Status bool `json:"status"`
}

type FileStatusRes struct {
	Base
}

type FileUploadReq struct {
	Hash     string `json:"hash,optional"`
	FileName string `json:"file_name,optional"`
	Ext      string `json:"ext,optional"`
	Size     int64  `json:"size,optional"`
	FilePath string `json:"file_path,optional"`
}

type FileUploadRes struct {
	Base
	Data FileUploadResdata `json:"data"`
}

type FileUploadResdata struct {
	FileName string `json:"file_name"`
	Path     string `json:"path"`
}

type InfoCategorieReq struct {
	UserId uint `form:"user_id"`
}

type InfoCategorieRes struct {
	Base
	Data InfoCategorieResData `json:"data"`
}

type InfoCategorieResData struct {
	Info []CategorieInfo `json:"info"`
}

type InfoUserReq struct {
	Id uint `form:"id"`
}

type InfoUserRes struct {
	Base
	Data InfoUserResData `json:"data"`
}

type InfoUserResData struct {
	Id              uint   `json:"id"`
	Username        string `json:"username"`
	Motto           string `json:"motto"`
	Avatar          string `json:"avatar"`
	Cover           string `json:"cover"`
	BlogCount       int64  `json:"blog_count"`
	WallpaperCount  int64  `json:"wallpaper_count"`
	TagsCount       int64  `json:"tags_count"`
	CategoriesCount int64  `json:"categories_count"`
}

type ListBlogItem struct {
	Id         uint             `json:"id"`
	Uid        string           `json:"uid"`
	Created    int64            `json:"created"`
	Updated    int64            `json:"updated"`
	Title      string           `json:"title"`
	Des        string           `json:"des"`
	Cover      string           `json:"cover"`
	Content    string           `json:"content"`
	UserId     uint             `json:"user_id"`
	Keywords   string           `json:"keywords"`
	User       BlogUserInfo     `json:"user" gorm:"column:User;reference:UserId"`
	Tag        []*BlogTags      `json:"tag" gorm:"column:Tag;many2many:article_tag"`
	Comment    []BlogComments   `json:"comment" gorm:"column:Comment"`
	Categories BlogCategoryInfo `json:"categories"`
}

type ListBlogReq struct {
	Page  int    `form:"page"`
	Limit int    `form:"limit"`
	Type  string `form:"type,optional,options=[top,recently,created]"`
}

type ListBlogRes struct {
	Base
	Data ListBlogResData `json:"data"`
}

type ListBlogResData struct {
	Count int64          `json:"count"`
	List  []ListBlogItem `json:"list"`
}

type ListTagReq struct {
	Type string `form:"type,options=[image,article]"`
}

type ListTagRes struct {
	Base
	Data ListTagResData `json:"data"`
}

type ListTagResData struct {
	Tags []TagInfo `json:"tags"`
}

type ListTagUserIdReq struct {
	UserId uint   `form:"user_id,optional"`
	Type   string `form:"type,options=[image,article]"`
}

type ListTagUserIdRes struct {
	Base
	Data ListTagUserIdResData `json:"data"`
}

type ListTagUserIdResData struct {
	Tags []TagInfo `json:"tags"`
}

type SearchReq struct {
	Keyword string `form:"keyword"`
	Type    string `form:"type,options=[article,images]"`
}

type SearchRes struct {
	Base
	Data SearchResData `json:"data"`
}

type SearchResData struct {
	Infos []SearchResDataInfo `json:"infos"`
}

type SearchResDataInfo struct {
	Id      uint   `json:"id"`
	Uid     string `json:"uid"`
	Created int64  `json:"created"`
	Title   string `json:"title"`
	Des     string `json:"des"`
	Cover   string `json:"cover"`
}

type SignInReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignInRes struct {
	Base
	Data SignInResData `json:"data"`
}

type SignInResData struct {
	UserInfo UserInfo `json:"user_info"`
	Token    string   `json:"token"`
}

type SignUpReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type SignUpRes struct {
	Base
}

type TagInfo struct {
	Id      uint           `json:"id" form:"id" gorm:"primaryKey"`
	Uid     string         `json:"uid" form:"uid"`
	TagName string         `json:"tag_name" form:"tag_name"`
	Type    string         `json:"type" form:"type" gorm:"type:enum('image', 'article')"`
	Article []*ArticleInfo `json:"articles" gorm:"column:Article;many2many:article_tag"`
}

type UpdateBlogReq struct {
	Id         uint   `json:"id"`
	Title      string `json:"title"`
	Des        string `json:"des"`
	Cover      string `json:"cover"`
	Content    string `json:"content"`
	Keywords   string `json:"keywords"`
	Tags       []uint `json:"tags,optional"`
	CategoryId uint   `json:"category_id,optional"`
}

type UpdateBlogRes struct {
	Base
}

type UpdateCategorieReq struct {
	Id    uint   `json:"id"`
	Cover string `json:"cover"`
	Name  string `json:"name"`
	Des   string `json:"des"`
}

type UpdateCategorieRes struct {
	Base
}

type UpdateTagReq struct {
	Id   uint   `json:"id"`
	Name string `json:"name"`
}

type UpdateTagRes struct {
	Base
}

type UpdateUserPasswordReq struct {
	Password string `json:"password"`
}

type UpdateUserPasswordRes struct {
	Base
}

type UpdateUserReq struct {
	Id       uint   `json":"id"`
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
	Motto    string `json:"motto,optional"`
	Address  string `json:"address,optional"`
	Tel      int    `json:"tel,optional"`
	Email    string `json:"email,optional"`
	QQ       int    `json:"qq,optional"`
	Wechat   string `json:"wechat,optional"`
	GitHub   string `json:"git_hub,optional"`
	Cover    string `json:"cover,optional"`
}

type UpdateUserRes struct {
	Base
}

type UserInfo struct {
	Id       uint   `json:"id"`
	Uid      string `json:"uid"`
	Username string `json:"username"`
	Cover    string `json:"cover"`
	Avatar   string `json:"avatar"`
	Account  string `json:"account"`
	Motto    string `json:"motto"`
	Address  string `json:"address"`
	Tel      int    `json:"tel"`
	Email    string `json:"email"`
	QQ       int    `json:"qq"`
	Wechat   string `json:"wechat"`
	GitHub   string `json:"git_hub"`
}
