// Code generated by goctl. DO NOT EDIT.
package types

type BlogSearchByIdReq struct {
	Id uint `form:"id"`
}

type BlogSearchByIdRes struct {
	Info ListBlogItem `json:"info"`
}

type BlogTags struct {
	Id      uint   `json:"id" json:"id"`
	Uid     string `json:"uid"`
	TagName string `json:"tag_name""`
	Type    string `json:"type"`
}

type BlogUserInfo struct {
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Motto    string `json:"motto"`
}

type CreateBlogReq struct {
	Title   string `json:"title"`
	Des     string `json:"des"`
	Cover   string `json:"cover"`
	Content string `json:"content"`
	Tags    []uint `json:"tags,optional"`
}

type CreateBlogRes struct {
	Id      uint   `json:"id"`
	Message string `json:"message"`
}

type CreateTagReq struct {
	Name string `json:"name"`
	Type string `json:"type,options=[article,image]"`
}

type CreateTagRes struct {
	Message string `json:"message"`
}

type DeleteBlogReq struct {
	Id uint `json:"id"`
}

type DeleteBlogRes struct {
	Message string `json:"message"`
}

type DeleteTagReq struct {
	Id uint `json:"id"`
}

type DeleteTagRes struct {
	Message string `json:"message"`
}

type FileInfo struct {
	Id       uint   `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
}

type FileListReq struct {
	Page  int    `form:"page"`
	Limit int    `form:"limit"`
	Type  string `form:"type,options=[blog,image,avatar]"`
}

type FileListRes struct {
	Count int64      `json:"count"`
	Infos []FileInfo `json:"infos"`
}

type FileUploadReq struct {
	Hash     string `json:"hash,optional"`
	FileName string `json:"file_name,optional"`
	Ext      string `json:"ext,optional"`
	Size     int64  `json:"size,optional"`
	FilePath string `json:"file_path,optional"`
}

type FileUploadRes struct {
	FileName string `json:"file_name"`
	Path     string `json:"path"`
}

type ListBlogItem struct {
	Id      uint         `json:"id"`
	Uid     string       `json:"uid"`
	Created int64        `json:"created"`
	Updated int64        `json:"updated"`
	Title   string       `json:"title"`
	Des     string       `json:"des"`
	Cover   string       `json:"cover"`
	Content string       `json:"content"`
	UserId  uint         `json:"user_id"`
	User    BlogUserInfo `json:"user" gorm:"column:User;reference:UserId"`
	Tag     []*BlogTags  `json:"tag" gorm:"column:Tag;many2many:article_tag"`
}

type ListBlogReq struct {
	Page  int `form:"page"`
	Limit int `form:"limit"`
}

type ListBlogRes struct {
	Count int64          `json:"count"`
	List  []ListBlogItem `json:"list"`
}

type SignInReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignInRes struct {
	UserInfo UserInfo `json:"user_info"`
	Token    string   `json:"token"`
}

type SignUpReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type SignUpRes struct {
	Message string `json:"message"`
}

type UpdateBlogReq struct {
	Id      uint   `json:"id"`
	Title   string `json:"title"`
	Des     string `json:"des"`
	Cover   string `json:"cover"`
	Content string `json:"content"`
	Tags    []uint `json:"tags"`
}

type UpdateBlogRes struct {
	Message string `json:"message"`
}

type UpdateTagReq struct {
	Id   uint   `json:"id"`
	Name string `json:"name"`
}

type UpdateTagRes struct {
	Message string `json:"message"`
}

type UpdateUserPasswordReq struct {
	Password string `json:"password"`
}

type UpdateUserReq struct {
	Id       uint   `json":"id"`
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
	Motto    string `json:"motto,optional"`
	Address  string `json:"address,optional"`
	Tel      int    `json:"tel,optional"`
	Email    string `json:"email,optional"`
	QQ       int    `json:"qq,optional"`
	Wechat   string `json:"wechat,optional"`
	GitHub   string `json:"git_hub,optional"`
}

type UpdateUserRes struct {
	Message string `json:"message"`
}

type UserInfo struct {
	Id       uint   `json:"id"`
	Uid      string `json:"uid"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Account  string `json:"account"`
	Motto    string `json:"motto"`
	Address  string `json:"address"`
	Tel      int    `json:"tel"`
	Email    string `json:"email"`
	QQ       int    `json:"qq"`
	Wechat   string `json:"wechat"`
	GitHub   string `json:"git_hub"`
}
